language: node_js
node_js:
 - "node"
 addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g bower gulp-cli@1
- bower install
- gulp lint-eslint
env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST
