# sudo: required
dist: trusty
language: node_js
node_js: stable
addons:
  firefox: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - npm install -g bower polymer-cli
  - bower install
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
script: polymer test


# language: node_js
# node_js: stable
# dist: trusty
# addons:
#   firefox: latest
#   chrome: stable
# before_script:
# # - "export DISPLAY=:99.0"
# # - "sh -e /etc/init.d/xvfb start"
# # - sleep 3 # give xvfb some time to start
# - npm install -g bower polymer-cli
# - npm install
# # browserstack-local
# - bower install
# cache:
#   directories:
#     - node_modules
#     - $HOME/.cache/bower
# script:
# #  - polymer test
# - xvfb-run polymer test
# - xvfb-run wct -l chrome
# - xvfb-run wct -l firefox
# addons:
#   browserstack:
#     username: marcusweaver1
#     access_key:
#       secure: MAz2JAV/GArMqfGnoHfsBheO08vnAVnSbzAogZEHR0KGZDZV7pfUffi1E8/qiyDGomQkzk3dHJaMro6hXc5LhYV0wc4QqueHOT/4rNxrYyw2QeBZD8LyXPe3WWx3VY4Zs3UwFvrEhtAPGuiEL4REXbsFNqnxX2INmU+6p1pY4L+uUmvefG5eMoCaP4OzmbUaQNgljNKCzfYM/Yq9b4GNjzX8WOF6Gb2Kiu7lNF2y4j8y2l1VZwYEu/C0SX42niN2qjY6YIeLABxZBnRFCDIJDG9QDsiKU7ToYITRBbATQrkxcLgeiBqNG9hXYjAkwLiZnvrwkMuokWemBwOLfHWuDA16HAhwZhBryy3MObq7iR3FKvozoGLXYEnVfq+fUC+BVwiFFAPg06MtbuKo9IH/xVmgNxmwziUhMpxZpdL/r0ouBjEpTNoHQz0FmoOj5cCIgZdiKQZeS0MA/YY8MH9xxiJxZnl7iFPcH8Ob4xm4qM6EUZvCYiAZ2FacP1B84nnnPemCHYHyB1PMmM/NAFEcCm3+ISBt1wF5OD/DX/z65Ahy7zIlhjngPd9Nl+/pfxskFzYJ/8pH67HEmAP9gN3lQx4uQE4CTm6JwQpjLvk+TmayeWFKfQLJR7UJPwAdgj5IYlYWXnsOM9A7qy6qxStwpD+7iZYb/XQHkliKOdIfYa8=
#     forcelocal: true
#     only: 192.168.0.107,8080,0